source 'https://github.com/CocoaPods/Specs.git'
use_modular_headers!
platform :ios, '10.0'

target 'XKBaseAlert_Example' do
  pod 'XKBaseAlert', :path => '../'

  target 'XKBaseAlert_Tests' do
    inherit! :search_paths

    
  end
end
